import type { LedgerEntry, LedgerState, Requirement, TestRun } from './types';

function formatDate(value: string): string {
  if (!value) return 'Not recorded';
  return new Intl.DateTimeFormat('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date(value));
}

function requirementLine(req: Requirement): string {
  return `- [${req.status === 'verified' ? 'x' : ' '}] ${req.priority} ${req.title} (${req.status})`;
}

function runLine(run: TestRun): string {
  return [
    `### ${run.label}`,
    '',
    `- Status: ${run.status}`,
    `- Target URL: ${run.targetUrl || 'Not recorded'}`,
    `- Duration: ${run.durationSec}s`,
    `- Credits: ${run.credits.toFixed(2)}`,
    `- Command: \`${run.command || 'Not recorded'}\``,
    `- Notes: ${run.notes || 'None'}`,
  ].join('\n');
}

function entryLine(entry: LedgerEntry): string {
  return [
    `### ${entry.title}`,
    '',
    `- Kind: ${entry.kind}`,
    `- Status: ${entry.status}`,
    `- Captured: ${formatDate(entry.createdAt)}`,
    `- Evidence: ${entry.evidence || 'Not recorded'}`,
    '',
    entry.detail || 'No detail recorded.',
  ].join('\n');
}

export function generateLoopMarkdown(state: LedgerState): string {
  const { project, requirements, runs, entries } = state;
  const passed = runs.filter(run => run.status === 'passed').length;
  const totalCredits = runs.reduce((sum, run) => sum + run.credits, 0);

  return [
    `# LOOP.md - ${project.name || 'LoopLedger Project'}`,
    '',
    '## Submission Context',
    '',
    `- Live URL: ${project.liveUrl || 'Not recorded'}`,
    `- Repository: ${project.repoUrl || 'Not recorded'}`,
    `- Primary CLI command: \`${project.testCommand || 'Not recorded'}\``,
    `- Goal: ${project.submissionGoal || 'Not recorded'}`,
    '',
    '## Requirements',
    '',
    ...(requirements.length > 0 ? requirements.map(requirementLine) : ['No requirements recorded.']),
    '',
    '## TestSprite CLI Runs',
    '',
    `Summary: ${passed}/${runs.length} passing, ${totalCredits.toFixed(2)} credits tracked.`,
    '',
    ...(runs.length > 0 ? runs.map(runLine) : ['No CLI runs recorded.']),
    '',
    '## Evidence Ledger',
    '',
    ...(entries.length > 0 ? entries.map(entryLine) : ['No ledger entries recorded.']),
    '',
    '## Final Notes',
    '',
    'This file was generated by LoopLedger from tracked requirements, CLI run evidence, failure notes, fixes, and reruns.',
  ].join('\n');
}
